//! DSPF (Detailed Standard Parasitic Format) writer.

use super::graph::{PexGraph, PexNode, TerminalRef};
use std::collections::HashMap;
use std::io::Write;

/// Format a node name: "net_name:segment" or "net_name" for terminal nodes.
fn node_name(node: &PexNode, net_names: &HashMap<u32, String>) -> String {
    let net = net_names
        .get(&node.net_id)
        .cloned()
        .unwrap_or_else(|| format!("N{}", node.net_id));
    match node.segment {
        Some(s) => format!("{}:{}", net, s),
        None => net,
    }
}

fn net_name(net_id: u32, net_names: &HashMap<u32, String>) -> String {
    net_names
        .get(&net_id)
        .cloned()
        .unwrap_or_else(|| format!("N{}", net_id))
}

fn direction_str(terminal: &Option<TerminalRef>) -> &'static str {
    match terminal {
        Some(TerminalRef::Port(_)) => "B", // bidirectional for ports
        Some(_) => "I",                    // internal device terminal
        None => "I",
    }
}

/// Write the parasitic graph in DSPF format.
pub fn write_dspf(
    graph: &PexGraph,
    net_names: &HashMap<u32, String>,
    cell_name: &str,
    out: &mut dyn Write,
) -> std::io::Result<()> {
    writeln!(out, "*|DESIGN \"{}\"", cell_name)?;
    writeln!(out, "*|DATE \"generated by gdsverify PEX\"")?;
    writeln!(out)?;

    // Collect unique nets
    let mut nets: Vec<u32> = graph.nodes.iter().map(|n| n.net_id).collect();
    nets.sort_unstable();
    nets.dedup();

    for &nid in &nets {
        let total_cap = graph.total_cap_on_net(nid);
        let nname = net_name(nid, net_names);
        writeln!(out, "*|NET {} {:.6}PF", nname, total_cap * 1e-3)?; // aF → pF (÷1000)

        // Terminal pins
        for node in graph
            .nodes
            .iter()
            .filter(|n| n.net_id == nid && n.terminal.is_some())
        {
            let nn = node_name(node, net_names);
            let dir = direction_str(&node.terminal);
            writeln!(out, "*|I ({} {})", nn, dir)?;
        }

        // Subnodes
        for node in graph.nodes.iter().filter(|n| n.net_id == nid) {
            let nn = node_name(node, net_names);
            writeln!(out, "*|S ({} {} {})", nn, node.x, node.y)?;
        }
        writeln!(out)?;
    }

    // Resistors
    let mut ri = 1_u32;
    for edge in &graph.edges {
        let from_node = graph.nodes.iter().find(|n| n.id == edge.from);
        let to_node = graph.nodes.iter().find(|n| n.id == edge.to);
        let (fn_name, tn_name) = match (from_node, to_node) {
            (Some(f), Some(t)) => (node_name(f, net_names), node_name(t, net_names)),
            _ => continue,
        };
        writeln!(
            out,
            "R{} {} {} {:.6}",
            ri, fn_name, tn_name, edge.resistance_ohm
        )?;
        ri += 1;
    }

    // Ground capacitors
    let mut ci = 1_u32;
    for &(nid, cap) in &graph.ground_caps {
        if let Some(node) = graph.nodes.iter().find(|n| n.id == nid) {
            let nn = node_name(node, net_names);
            writeln!(out, "C{} {} 0 {:.6}F", ci, nn, cap * 1e-18)?; // aF → F
            ci += 1;
        }
    }
    // Substrate caps from nodes
    for node in &graph.nodes {
        if node.substrate_cap_af > 0.0 {
            let nn = node_name(node, net_names);
            writeln!(
                out,
                "C{} {} 0 {:.6}F",
                ci,
                nn,
                node.substrate_cap_af * 1e-18
            )?;
            ci += 1;
        }
    }

    // Coupling caps
    for &(a, b, cap) in &graph.coupling_caps {
        let an = graph.nodes.iter().find(|n| n.id == a);
        let bn = graph.nodes.iter().find(|n| n.id == b);
        if let (Some(an), Some(bn)) = (an, bn) {
            writeln!(
                out,
                "C{} {} {} {:.6}F",
                ci,
                node_name(an, net_names),
                node_name(bn, net_names),
                cap * 1e-18
            )?;
            ci += 1;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::geometry::PolyId;
    use crate::graph::{PexEdge, PexEdgeKind, PexNode};

    #[test]
    fn dspf_output_contains_design_header() {
        let mut g = PexGraph::new();
        g.add_node(PexNode {
            id: 0,
            net_id: 1,
            layer: 0,
            poly: PolyId(0),
            segment: None,
            x: 0,
            y: 0,
            terminal: None,
            substrate_cap_af: 5.0,
        });
        g.add_node(PexNode {
            id: 1,
            net_id: 1,
            layer: 0,
            poly: PolyId(0),
            segment: Some(1),
            x: 100,
            y: 0,
            terminal: None,
            substrate_cap_af: 5.0,
        });
        g.add_edge(PexEdge {
            from: 0,
            to: 1,
            resistance_ohm: 2.5,
            kind: PexEdgeKind::Wire,
            layer: 0,
            inductance_nh: None,
        });
        let mut names = HashMap::new();
        names.insert(1_u32, "VDD".to_string());

        let mut buf = Vec::new();
        write_dspf(&g, &names, "top", &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("*|DESIGN \"top\""));
        assert!(s.contains("*|NET VDD"));
        assert!(s.contains("R1 VDD VDD:1 2.5"));
    }
}
