[package]
name = "gdsverify"
version = "0.1.0"
edition = "2021"

[features]
gpu = [
    "gdsverify-backend/gpu",
    "gdsverify-core/gpu",
    "gdsverify-drc/gpu",
    "gdsverify-erc/gpu",
    "gdsverify-lvs/gpu",
    "gdsverify-pex/gpu",
]

[dependencies]
gdsverify-backend = { path = "../crates/backend" }
gdsverify-core = { path = "../crates/core" }
gdsverify-drc = { path = "../crates/drc" }
gdsverify-erc = { path = "../crates/erc" }
gdsverify-lvs = { path = "../crates/lvs" }
gdsverify-pex = { path = "../crates/pex_analytical" }
gdsverify-macros = { path = "../macros" }
serde = { workspace = true }
serde_json = { workspace = true }
