[package]
name = "gdsverify-erc"
version = "0.1.0"
edition = "2021"

[features]
gpu = ["gdsverify-backend/gpu", "gdsverify-core/gpu"]

[dependencies]
gdsverify-backend = { path = "../backend" }
gdsverify-core = { path = "../core" }
gdsverify-lvs = { path = "../lvs" }
gdsverify-pex = { path = "../pex_analytical" }
gdsverify-macros = { path = "../../macros" }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
# rules/ glob

[dev-dependencies]
gdsverify = { path = "../../engine" }
