[package]
name = "gpurify-ingest"
version = "0.1.0"
edition = "2021"

[dependencies]
gpurify-geom = { workspace = true }
thiserror = { workspace = true }
fearless_simd = { workspace = true }
flate2 = { workspace = true }
# The design intent is JSON.
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
gpurify-testgen = { workspace = true }

[lints]
workspace = true
