use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();

    let dir = Path::new(&manifest).join("src").join("rules");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut names: Vec<String> = match fs::read_dir(&dir) {
        Ok(entries) => entries
            .filter_map(|entry| {
                let path = entry.ok()?.path();
                if path.extension()? != "rs" {
                    return None;
                }
                Some(path.file_stem()?.to_str()?.to_string())
            })
            .collect(),
        Err(_) => Vec::new(),
    };
    names.sort();

    let dir_str = dir.display().to_string().replace('\\', "/");
    let mut code =
        String::from("// @generated by build.rs — compile-time glob of the rules/ folder.\n");
    for name in &names {
        code.push_str(&format!(
            "#[path = \"{dir_str}/{name}.rs\"]\npub mod {name};\n"
        ));
    }
    code.push_str("\n/// Every rule in this engine's rules/ folder, globbed at compile time.\n");
    code.push_str("pub static FACTORIES: &[Factory] = &[\n");
    for name in &names {
        code.push_str(&format!("    {name}::FACTORY,\n"));
    }
    code.push_str("];\n");

    fs::write(Path::new(&out_dir).join("pex_rules.rs"), code).unwrap();
}
