//! SPEF (Standard Parasitic Exchange Format, IEEE 1481-1998) writer.

use super::graph::{PexGraph, PexNode, TerminalRef};
use std::collections::HashMap;
use std::io::Write;

fn node_name(node: &PexNode, net_names: &HashMap<u32, String>) -> String {
    let net = net_names
        .get(&node.net_id)
        .cloned()
        .unwrap_or_else(|| format!("N{}", node.net_id));
    match node.segment {
        Some(s) => format!("{}:{}", net, s),
        None => net,
    }
}

fn net_name(net_id: u32, net_names: &HashMap<u32, String>) -> String {
    net_names
        .get(&net_id)
        .cloned()
        .unwrap_or_else(|| format!("N{}", net_id))
}

fn direction_str(terminal: &Option<TerminalRef>) -> &'static str {
    match terminal {
        Some(TerminalRef::Port(_)) => "B",
        Some(TerminalRef::Gate(_)) => "I",
        Some(TerminalRef::Drain(_) | TerminalRef::Source(_)) => "I",
        Some(_) => "I",
        None => "I",
    }
}

/// Write the parasitic graph in SPEF format.
pub fn write_spef(
    graph: &PexGraph,
    net_names: &HashMap<u32, String>,
    cell_name: &str,
    out: &mut dyn Write,
) -> std::io::Result<()> {
    writeln!(out, "*SPEF \"IEEE 1481-1998\"")?;
    writeln!(out, "*DESIGN \"{}\"", cell_name)?;
    writeln!(out, "*DATE \"generated by gdsverify PEX\"")?;
    writeln!(out, "*VENDOR \"gdsverify\"")?;
    writeln!(out, "*PROGRAM \"gdsverify\"")?;
    writeln!(out, "*VERSION \"0.1\"")?;
    writeln!(out, "*DESIGN_FLOW \"LAYOUT_X\"")?;
    writeln!(out, "*DIVIDER /")?;
    writeln!(out, "*DELIMITER :")?;
    writeln!(out, "*BUS_DELIMITER [ ]")?;
    writeln!(out, "*T_UNIT 1 NS")?;
    writeln!(out, "*C_UNIT 1 FF")?; // femtofarads
    writeln!(out, "*R_UNIT 1 OHM")?;
    writeln!(out, "*L_UNIT 1 HENRY")?;
    writeln!(out)?;

    let mut nets: Vec<u32> = graph.nodes.iter().map(|n| n.net_id).collect();
    nets.sort_unstable();
    nets.dedup();

    for &nid in &nets {
        let total_cap = graph.total_cap_on_net(nid);
        let nname = net_name(nid, net_names);
        // C_UNIT is FF; total_cap is in aF → ÷1000
        writeln!(out, "*D_NET {} {:.6}", nname, total_cap * 1e-3)?;

        // *CONN section
        writeln!(out, "*CONN")?;
        for node in graph
            .nodes
            .iter()
            .filter(|n| n.net_id == nid && n.terminal.is_some())
        {
            let nn = node_name(node, net_names);
            let dir = direction_str(&node.terminal);
            writeln!(out, "*I {} {}", nn, dir)?;
        }

        // *CAP section
        writeln!(out, "*CAP")?;
        let mut ci = 1_u32;
        // Ground caps
        for &(node_id, cap) in &graph.ground_caps {
            if let Some(node) = graph
                .nodes
                .iter()
                .find(|n| n.id == node_id && n.net_id == nid)
            {
                let nn = node_name(node, net_names);
                writeln!(out, "{} {} {:.6}", ci, nn, cap * 1e-3)?; // aF → fF
                ci += 1;
            }
        }
        // Substrate caps
        for node in graph
            .nodes
            .iter()
            .filter(|n| n.net_id == nid && n.substrate_cap_af > 0.0)
        {
            let nn = node_name(node, net_names);
            writeln!(out, "{} {} {:.6}", ci, nn, node.substrate_cap_af * 1e-3)?;
            ci += 1;
        }
        // Coupling caps involving this net
        for &(a, b, cap) in &graph.coupling_caps {
            let an = graph.nodes.iter().find(|n| n.id == a);
            let bn = graph.nodes.iter().find(|n| n.id == b);
            if let (Some(an), Some(bn)) = (an, bn) {
                if an.net_id == nid {
                    writeln!(
                        out,
                        "{} {} {} {:.6}",
                        ci,
                        node_name(an, net_names),
                        node_name(bn, net_names),
                        cap * 1e-3
                    )?;
                    ci += 1;
                }
            }
        }

        // *RES section
        writeln!(out, "*RES")?;
        let mut ri = 1_u32;
        let net_node_ids: Vec<u32> = graph
            .nodes
            .iter()
            .filter(|n| n.net_id == nid)
            .map(|n| n.id)
            .collect();
        for edge in &graph.edges {
            // Include edges that have at least one endpoint on this net
            if net_node_ids.contains(&edge.from) || net_node_ids.contains(&edge.to) {
                let fn_name = graph
                    .nodes
                    .iter()
                    .find(|n| n.id == edge.from)
                    .map(|n| node_name(n, net_names))
                    .unwrap_or_else(|| format!("?{}", edge.from));
                let tn_name = graph
                    .nodes
                    .iter()
                    .find(|n| n.id == edge.to)
                    .map(|n| node_name(n, net_names))
                    .unwrap_or_else(|| format!("?{}", edge.to));
                writeln!(
                    out,
                    "{} {} {} {:.6}",
                    ri, fn_name, tn_name, edge.resistance_ohm
                )?;
                ri += 1;
            }
        }

        writeln!(out, "*END")?;
        writeln!(out)?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::geometry::PolyId;
    use crate::graph::{PexEdge, PexEdgeKind, PexNode};

    #[test]
    fn spef_output_contains_header_and_net() {
        let mut g = PexGraph::new();
        g.add_node(PexNode {
            id: 0,
            net_id: 1,
            layer: 0,
            poly: PolyId(0),
            segment: None,
            x: 0,
            y: 0,
            terminal: Some(TerminalRef::Port("A".into())),
            substrate_cap_af: 3.0,
        });
        g.add_node(PexNode {
            id: 1,
            net_id: 1,
            layer: 0,
            poly: PolyId(0),
            segment: Some(1),
            x: 50,
            y: 0,
            terminal: None,
            substrate_cap_af: 2.0,
        });
        g.add_edge(PexEdge {
            from: 0,
            to: 1,
            resistance_ohm: 1.5,
            kind: PexEdgeKind::Wire,
            layer: 0,
            inductance_nh: None,
        });
        g.ground_caps.push((0, 10.0));

        let mut names = HashMap::new();
        names.insert(1_u32, "clk".to_string());

        let mut buf = Vec::new();
        write_spef(&g, &names, "top", &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("*SPEF \"IEEE 1481-1998\""));
        assert!(s.contains("*DESIGN \"top\""));
        assert!(s.contains("*D_NET clk"));
        assert!(s.contains("*I clk B")); // port is bidirectional
        assert!(s.contains("*CAP"));
        assert!(s.contains("*RES"));
        assert!(s.contains("*END"));
    }
}
